config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope 'api' do
    namespace 'v1' do
      scope module: 'app' do
        post 'sessions' => 'sessions#create'
        delete 'sessions' => 'sessions#destroy'
        get 'boot' => 'boot#show'

        resources 'business_types'
        resources 'companies'
        resources 'users'
        resources 'customers'
        resources 'services'
        resources 'visits'
        resources 'events', only: [:index]
      end

      namespace 'public' do
        resources 'business_types'
      end

      namespace 'mobile' do
        resources 'companies', only: [:index, :show]
        resources 'services', only: [:index, :show]
        resources 'business_types', only: [:index]
        resources 'visits', only: [:create]
      end
    end
  end

  resource :registration, only: [:new, :create, :thanks] do
    get 'thanks', :on => :member
  end

  resource :public_message, only: [:new, :create, :thanks] do
    get 'thanks', :on => :member
  end

  root to: 'landing_page#index'
end

app/models/public_message.rb
class PublicMessage < ApplicationRecord
  validates :company_name, presence: true
  validates :email, presence: true
  validates :message, presence: true
  validates :name, presence: true
  validates :phone, presence: true
end

app/controllers/public_messages_controller.rb
class PublicMessagesController < ActionController::Base
  layout 'landing_page'

  def new
  end

  def thanks
  end

  def create
    public_message = PublicMessage.create(public_message_params)
    PublicMailer.notification_to_office_email(public_message).deliver_now
    PublicMailer.notification_to_client_email(public_message).deliver_now

    redirect_to thanks_public_message_path
  end

  private

  def public_message_params
    params.require(:public_message).permit(:company_name, :email, :message, :name, :phone)
  end
end

app/views/public_messages/new.html.erb
<%= render "shared/header" %>

<div class="c-landing-page__content c-contact-page__content h-inner">
  <div class="c-contact-page__content__form-wrapper">
    <h1 class="c-heading u-margin-bottom--30">Napisz do nas</h1>

    <%= form_for :public_message, url: public_message_path, html: { class: "c-contact-page__content__form" } do |f| %>
      <div>
        <label>
          <span>Imię i nazwisko</span>
          <input type="text" name="public_message[name]" class="c-input" />
          <i class="c-input__error u-display--none">Wprowadź imię i nazwisko</i>
        </label>

        <label>
          <span>Email</span>
          <input type="email" name="public_message[email]" class="c-input" />
          <i class="c-input__error u-display--none">Wprowadź poprawny email</i>
        </label>
      </div>

      <div class="u-margin-top--30">
        <label>
          <span>Numer telefonu</span>
          <input type="phone" name="public_message[phone]" class="c-input" />
        </label>

        <label>
          <span>Nazwa firmy</span>
          <input type="text" name="public_message[company_name]" class="c-input" />
        </label>
      </div>

      <div class="u-margin-top--30">
        <label class="u-width--full u-margin--none">
          <span>Wiadomość</span>
          <textarea name="public_message[message]" class="c-input c-input--textarea"></textarea>
          <i class="c-input__error u-display--none">Wprowadź wiadomość</i>
        </label>
      </div>

      <input type="submit" value="Wyślij wiadomość" class="c-button c-button--filled c-button--filled-purple u-margin-top--30" disabled />
    <% end %>
  </div>

  <div class="c-contact-page__content__svg-wrapper">
    <%= inline_svg_tag "contact_page_message.svg" %>
  </div>
</div>

app/views/public_messages/thanks.html.erb
<%= render "shared/header" %>

<div class="c-registration-thanks-page__content h-inner">
  <h1 class="c-heading u-margin-bottom--30">Dziękujemy za kontakt!</h1>
  <p>Zapoznamy się z Twoją wiadomością i odpowiemy tak szybko jak to tylko możliwe.</p>
</div>