config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope 'api' do
    namespace 'v1' do
      scope module: 'app' do
        post 'sessions' => 'sessions#create'
        delete 'sessions' => 'sessions#destroy'
        get 'boot' => 'boot#show'

        resources 'business_types'
        resources 'companies'
        resources 'users'
        resources 'customers'
        resources 'services'
        resources 'visits'
        resources 'events', only: [:index]
      end

      namespace 'public' do
        resources 'business_types'
      end

      namespace 'mobile' do
        resources 'companies', only: [:index, :show]
        resources 'services', only: [:index, :show]
        resources 'business_types', only: [:index]
        resources 'visits', only: [:create]
      end
    end
  end

  resource :registration, only: [:new, :create, :thanks] do
    get 'thanks', :on => :member
  end

  resource :public_message, only: [:new, :create, :thanks] do
    get 'thanks', :on => :member
  end

  root to: 'landing_page#index'
end

app/views/shared/_header.html.erb
<header class="c-header">
  <div class="h-inner">
    <a class="c-header__logo" href="/">
      Bookify
    </a>

    <nav class="c-header__nav-desktop">
      <%= link_to "Kontakt", new_public_message_path, class: "c-button c-button--text u-margin-right--20" %>
      <%= link_to "Zarejestruj się", new_registration_path, class: "c-button c-button--text u-margin-right--20" %>
      <a href="<%= ENV["REACT_HOST"] %>/signin" class="c-button c-button--filled">Zaloguj się</a>
    </nav>

    <nav class="c-header__nav-mobile">
      <%= fa_icon "bars", class: "c-header__nav-mobile__menu-icon c-header__nav-mobile__menu-icon--open" %>
      <%= fa_icon "times", class: "c-header__nav-mobile__menu-icon c-header__nav-mobile__menu-icon--close u-display--none" %>
    </nav>
  </div>

  <div class="c-header__nav-mobile-links">
    <%= link_to "Kontakt", new_public_message_path %>
    <%= link_to "Zarejestruj się", new_registration_path %>
    <a href="http://localhost:3001/signin">Zaloguj się</a>
  </div>
</header>